apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{. Release.Name }}-codelet-application
spec:
  selector:
    matchLabels:
      app: codelet-application
    templates:
      metadata:
        labels:
          app: codelet-application
      spec:
        containers:
          - name: {{. Value.containerName }}-codelet-application
            image: {{. Value.image }}
            ports:
            - containersPort: 80
        env:
          {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}   
