apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range $key, $val := .Values.service.targetPorts }}
  - name: {{ $key }}
    port: {{ $val }}
    targetPort: {{ $val }}
    protocol: TCP
 {{- end }}
