apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.service.name }}
  ports:
    {{- range $key, $val := .Values.service.targetPorts }}
  - name: {{ $key }}
    port: {{ $val }}
    targetPort: {{ $val }}
    protocol: TCP
 {{- end }}
