apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-codelet-application-ingress
spec:
  rules:
    - host: "localhost"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Release.Name }}-codelet-application-service
              port:
                number: 80