apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-codelet-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-codelet-application
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-codelet-application
    spec:
      containers:
        - name: {{ .Values.container.containerName }}-codelet-application
          image: {{ .Values.container.image.name }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
          - name: deployment-port
          - containerPort: {{ .Values.container.containerPort }}
          env:          
            {{- range $key, $val := .Values.container.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
         {{- end }}

