apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-codelet-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-codelet-application
  template:
    metadata:
      labels:
        app: {{ .Release.Name }} - codelet-application
    spec:
      containers:
        - name: {{ .Values.containerName }}-codelet-application
          image: {{ .Values.image }}
          ports:
          - containerPort: 8080
      env:
        {{- range .Values.env }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end -}}   
