apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.name }}
  ports:
    {{- range $key, $val := .Values.service.targetPorts }}
  - name: {{ $key }}
    port: {{ $val }}
    targetPort: {{ $val }}
    protocol: TCP
 {{- end }}
