apiVersion: v1
kind: Service
metadata:
  name: {{ .Service.name }}
spec:
  {{ if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{ end }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Release.Name }}-service
  ports:
    {{- range $key, $val := .Values.service.targetPorts }}
  - name: {{ $key }}
    port: {{ $val }}
    targetPort: {{ $val }}
    protocol: TCP
 {{- end }}
